language: python
dist: xenial
group: travis_latest

git:
  depth: 25
  quiet: true

install: pip install -e .[tests]

matrix:
  include:
  - os: linux
    python: 3.6
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls
#  - os: windows
#    language: minimal
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

script: pytest -rsv
