language: python
dist: xenial
group: travis_latest

git:
  depth: 25
  quiet: true

python:
- 3.6
- 3.7

install: pip install -e .[tests]

matrix:
  include:
  - os: linux
    name: Integration install
    python: 3.7
    install:
    - python setup.py install
    - pip install $(basename $TRAVIS_REPO_SLUG)[tests]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests -r a -v
  - os: linux
    name: PEP8 MyPy Cov
    python: 3.7
    install: pip install -e .[tests,lint]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls

script: pytest -r a -v
